; =====================================================================================================================
; === KasmOS (c)2025+ Laurent Menten (laurent.menten@gmail.com) === GNU Lesser General Public License v3.0 (LGPLv3) ===
; =====================================================================================================================

%ifndef __STRINGS_INC__
%define __STRINGS_INC__

	%include "strings_def.inc"

    extern _strlen
    extern _strcmp

%endif ;__STRINGS_INC__
