; =====================================================================================================================
; === KasmOS (c)2025+ Laurent Menten (laurent.menten@gmail.com) === GNU Lesser General Public License v3.0 (LGPLv3) ===
; =====================================================================================================================

%ifndef __STRINGS_DEF_INC__
%define __STRINGS_DEF_INC__


%endif ;__STRINGS_DEF_INC__
